channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.0
- pip:
  - mlflow==2.15.1
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - pandas==1.5.3
  - psutil==5.9.0
  - scikit-learn==1.4.2
  - xgboost==2.0.3
name: mlflow-env
